### ISSUE TITLE
Ask for permission for a lot 

### ISSUE THREAD

**Issue by Appsins** [HudsonOnHere/DiagnosticTool#1]
How can I stop asked for permission. 

Maybe once in the beginning or I can remove the disk read and write so he didn't ask for this all permissions?

thanks.

**Comment by HudsonOnHere** [comment]
Yes, this would be one way to stop the prompts.

In an enterprise setting, you can make allowances for certain programs to have different permissions - but this is only applicable if you're using an MDM solution. For most folks the easiest way is to just allow it.
